name = "webapp"
compatibility_date = "2026-01-04"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "webapp-production"
database_id = "4f2b491e-f8de-4bc0-85d1-a044b33cc4a5"

[browser]
binding = "MYBROWSER"
